//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bruttissimo.Domain.Logic.Email.Template.Account.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registered {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registered() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bruttissimo.Domain.Logic.Email.Template.Account.Resources.Registered", typeof(Registered).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu cuenta ya se encuentra creada y lista para usar..
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor confirma tu dirección de email haciendo click aquí.
        /// </summary>
        public static string AccountValidation {
            get {
                return ResourceManager.GetString("AccountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRUTTISSIMO!.
        /// </summary>
        public static string Bruttissimo {
            get {
                return ResourceManager.GetString("Bruttissimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeros pasos.
        /// </summary>
        public static string FirstSteps {
            get {
                return ResourceManager.GetString("FirstSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La era de la desinformación te está esperando....
        /// </summary>
        public static string LinkBackText {
            get {
                return ResourceManager.GetString("LinkBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esto te permitirá recuperar la contraseña en caso de perderla, e incluso recibir notificaciones via mail si así lo deseas..
        /// </summary>
        public static string OnValidation {
            get {
                return ResourceManager.GetString("OnValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qué esperás? Empezá a experimentar Bruttissimo ahora!.
        /// </summary>
        public static string Regards {
            get {
                return ResourceManager.GetString("Regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruttissimo consiste de una recopilación de las noticias más insólitas de la web, es una plataforma en la que nuestros usuarios pueden buscar, aportar y comentar sobre increibles hallazgos en el avanzado mundo tecnológico de la desinformación..
        /// </summary>
        public static string Sharing {
            get {
                return ResourceManager.GetString("Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido al mundo de lo insólito.
        /// </summary>
        public static string Teaser {
            get {
                return ResourceManager.GetString("Teaser", resourceCulture);
            }
        }
    }
}
