//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bruttissimo.Domain.Logic.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Smileys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Smileys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bruttissimo.Domain.Logic.Service.Resources.Smileys", typeof(Smileys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angel.
        /// </summary>
        internal static string Angel {
            get {
                return ResourceManager.GetString("Angel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sollozo.
        /// </summary>
        internal static string Cry {
            get {
                return ResourceManager.GetString("Cry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diablo.
        /// </summary>
        internal static string Devil {
            get {
                return ResourceManager.GetString("Devil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triste.
        /// </summary>
        internal static string Frown {
            get {
                return ResourceManager.GetString("Frown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorpresa.
        /// </summary>
        internal static string Gasp {
            get {
                return ResourceManager.GetString("Gasp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to felicidad.
        /// </summary>
        internal static string Grin {
            get {
                return ResourceManager.GetString("Grin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me gusta.
        /// </summary>
        internal static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amor.
        /// </summary>
        internal static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pacman.
        /// </summary>
        internal static string Pacman {
            get {
                return ResourceManager.GetString("Pacman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sonrisa.
        /// </summary>
        internal static string Smile {
            get {
                return ResourceManager.GetString("Smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lengüita.
        /// </summary>
        internal static string Tongue {
            get {
                return ResourceManager.GetString("Tongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guiño.
        /// </summary>
        internal static string Wink {
            get {
                return ResourceManager.GetString("Wink", resourceCulture);
            }
        }
    }
}
