ALTER TABLE [dbo].[RoleRight]
    ADD CONSTRAINT [PK_RoleRight] PRIMARY KEY CLUSTERED ([RoleId] ASC, [RightId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

