INSERT INTO [Smiley] (ResourceKey, Emoticon, Aliases, CssClass)
            SELECT 'Smile', ':)', ':-) :} :-} :] :-]', 'emoticon smile'
UNION ALL   SELECT 'Frown', ':(', ':-( :{ :-{ :[ :-[', 'emoticon frown'
UNION ALL   SELECT 'Wink', ';)', ';-) ;} ;-} ;] ;-]', 'emoticon wink'
UNION ALL   SELECT 'Tongue', ':P', ':-P ;P ;-P', 'emoticon tongue'
UNION ALL   SELECT 'Grin', ':D', ':-D ;D ;-D', 'emoticon grin'
UNION ALL   SELECT 'Gasp', ':O', ':-O ;O ;-O', 'emoticon gasp'
UNION ALL   SELECT 'Pacman', ':V', ':-V ;V ;-V', 'emoticon pacman'
UNION ALL   SELECT 'Cry', ':''(', ':''{ :''[', 'emoticon cry'
UNION ALL   SELECT 'Love', '<3', '(L) ♥ &hearts;', 'emoticon love'
UNION ALL   SELECT 'Devil', '3:)', '(6)', 'emoticon devil'
UNION ALL   SELECT 'Angel', 'O:)', '(A)', 'emoticon angel'
UNION ALL   SELECT 'Like', '(Y)', NULL, 'emoticon like'