//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bruttissimo.Common.Guard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bruttissimo.Common.Guard.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected to be a non-empty collection..
        /// </summary>
        internal static string EnsureExtensions_IsEmptyCollection {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected to be a non-empty Guid..
        /// </summary>
        internal static string EnsureExtensions_IsEmptyGuid {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected to be an object, but was type of: &apos;{0}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotClass {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected to be an object, but was NULL..
        /// </summary>
        internal static string EnsureExtensions_IsNotClass_WasNull {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotClass_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition evaluates to &apos;True&apos;. Expected &apos;False&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotFalse {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: value &apos;{0}&apos; is not greater than limit &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotGt {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: value &apos;{0}&apos; is not greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotGte {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotGte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: Expected length between &apos;{0}&apos; and &apos;{1}&apos; but value is &apos;{2}&apos; characters long..
        /// </summary>
        internal static string EnsureExtensions_IsNotInRange_String {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotInRange_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: value &apos;{0}&apos; is greater than &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotInRange_TooHigh {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotInRange_TooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: value &apos;{0}&apos; is lower than min &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotInRange_TooLow {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotInRange_TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: value &apos;{0}&apos; is not lower than &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotLt {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: value &apos;{0}&apos; is not lower than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotLte {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotLte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected to be non-null..
        /// </summary>
        internal static string EnsureExtensions_IsNotNull {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected to be non-null or empty..
        /// </summary>
        internal static string EnsureExtensions_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected to be non-null or blank..
        /// </summary>
        internal static string EnsureExtensions_IsNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The param is not of expected type: &apos;{0}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotOfType {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition evaluates to &apos;False&apos;. Expected &apos;True&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsNotTrue {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range: value &apos;{0}&apos; does not match &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_NoMatch {
            get {
                return ResourceManager.GetString("EnsureExtensions_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MemberExpression found in expression: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionUtils_GetRightMostMember_NoMemberFound {
            get {
                return ResourceManager.GetString("ExpressionUtils_GetRightMostMember_NoMemberFound", resourceCulture);
            }
        }
    }
}
