ALTER TABLE [dbo].[UserRoleRight]
    ADD CONSTRAINT [PK_UserRoleRight] PRIMARY KEY CLUSTERED ([UserRoleId] ASC, [UserRightId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

